<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.patrodyne.jvnet</groupId>
		<artifactId>hisrc-hyperjaxb-ejb-tests-jpa21</artifactId>
		<version>3.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>hisrc-hyperjaxb-ejb-tests-jpa21-code</artifactId>
	<packaging>jar</packaging>
	<name>HiSrc HyperJAXB EJB Test [jpa21-code]</name>

	<properties>
		<root.basedir>${basedir}/../../../..</root.basedir>
	</properties>

	<dependencies>

		<!-- JPA Dependencies -->
		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
		</dependency>

		<!-- Database Dependencies -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
		</dependency>

		<!-- SLF4J Implementation -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jul-to-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
		</dependency>

	</dependencies>

	<build>
		<defaultGoal>test</defaultGoal>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
			<resource>
				<directory>src/test/resources</directory>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<configuration>
					<mainClass>org.example.jpa21.Main</mainClass>
					<cleanupDaemonThreads>false</cleanupDaemonThreads>
				</configuration>
			</plugin>
			<plugin>
				<groupId>de.elnarion.maven</groupId>
				<artifactId>plantuml-generator-maven-plugin</artifactId>
				<executions>
					<execution>
						<?m2e ignore?>
						<id>generate-plantuml-diagram</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>process-classes</phase>
						<configuration>
							<scanPackages>
								<scanPackage>org.example.jpa21.model</scanPackage>
								<scanPackage>org.example.jpa21.other</scanPackage>
							</scanPackages>
							<blacklistRegexp>org\.example\.jpa21\.model\.(ObjectFactory|.*_)$</blacklistRegexp>
							<fieldClassifierListToIgnore>STATIC</fieldClassifierListToIgnore>
							<hideFields>false</hideFields>
							<removeMethods>true</removeMethods>
							<outputFilename>EmployeeClassesTemp.puml</outputFilename>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
