package org.jvnet.hyperjaxb.opt.eclipselink;

import java.io.IOException;
import java.io.Writer;

import org.eclipse.persistence.exceptions.ValidationException;
import org.eclipse.persistence.queries.ValueReadQuery;

/**
 * Custom H2Platform to fix field identity clause.
 * 
 * @see <a href="https://github.com/eclipse-ee4j/eclipselink/issues/1393">Issue #1393</a>
 */
public class H2Platform extends org.eclipse.persistence.platform.database.H2Platform
{
	private static final long serialVersionUID = 20230701L;
	
	/**
	 * Return a generated identity value from the last INSERT operation
	 * executed by application in this session.
	 * 
	 * @return {@link ValueReadQuery} Query read of a single data value.
	 */
	@Override 
	public ValueReadQuery buildSelectQueryForIdentity()
	{ 
		return new ValueReadQuery("CALL IDENTITY()"); 
	} 
	
	@Override
	public void printFieldIdentityClause(Writer writer)
		throws ValidationException
	{
        try
        {
            writer.append(" GENERATED BY DEFAULT AS IDENTITY");
        }
        catch (IOException ex)
        {
            throw ValidationException.logIOError(ex);
        }
	}
}
