package org.jvnet.hyperjaxb.opt.eclipselink.database;

import java.io.IOException;
import java.io.Writer;

import org.eclipse.persistence.exceptions.ValidationException;

/**
 * Custom PostgreSQL10Platform to fix field identity clause.
 *
 * @see <a href="https://github.com/eclipse-ee4j/eclipselink/issues/2644">Issue #2644</a>
 */
public class PostgreSQL10Platform extends org.eclipse.persistence.platform.database.PostgreSQL10Platform
{
	private static final long serialVersionUID = 20230701L;

    /**
     * CUSTOM: Append the receiver's field 'identity' constraint clause to a
     * writer.
     *
     * <p>PostgreSQL 10 introduced this standard syntax in October 2017.</p>
     */
	@Override
	public void printFieldIdentityClause(Writer writer)
		throws ValidationException
	{
        try
        {
            writer.append(" GENERATED BY DEFAULT AS IDENTITY");
        }
        catch (IOException ex)
        {
            throw ValidationException.logIOError(ex);
        }
	}
}
