package org.jvnet.hyperjaxb.item;

import java.io.Serializable;
import java.util.List;

/**
 * Default implementation of the {@link ItemList} interface.
 * <p>
 * This class provides a concrete bridge between a JAXB-managed list of
 * values (the {@code ListType}) and a core list of persistent JPA entities
 * (the {@code ItemType}). It ensures that all modifications to the
 * high-level list are reflected in the low-level persistence collection.
 * </p>
 * <p>
 * Instances of this class are typically created via the static factory
 * method {@link ItemList#create(Object)}.
 * </p>
 *
 * @param <ListType> generic type of the elements as they appear in the JAXB model.
 * @param <ItemType> generic type of the {@link Item} wrapper that stores the
 *                   value for JPA persistence.
 */
public class DefaultItemList<ListType, ItemType extends Item<ListType>>
	extends AbstractItemList<ListType, ItemType>
	implements Serializable
{
	private static final long serialVersionUID = -1941259574287915806L;
	private final Class<? extends ItemType> itemClass;

    /**
     * Constructs a new default item list backed by the specified
     * core collection.
     *
     * @param itemList the underlying list of persistent item wrappers.
     */
	public DefaultItemList(List<ItemType> itemList, final Class<? extends ItemType> itemClass)
	{
		super(itemList);
		this.itemClass = itemClass;
	}

	/**
	 * Returns the concrete class of the {@link Item} implementation
	 * managed by this list.
	 * <p>
	 * This method is used by the runtime to perform reflective
	 * instantiation of the {@code ItemType} when new elements are
	 * added to the JAXB list. Subclasses generated by HyperJAXB/BasicJAXB
	 * implement this to return the specific {@code .class} of the
	 * persistence wrapper (e.g., {@code MyEntityItem.class}).
	 * </p>
	 *
	 * @return the {@link Class} object representing the concrete
	 *         implementation of the persistent item.
	 */
	public Class<? extends ItemType> getItemClass()
	{
		return itemClass;
	}

	/**
	 * Creates a new persistent {@link Item} wrapper instance for the given value.
	 * <p>
	 * This implementation uses reflection in conjunction with {@link #getItemClass()}
	 * to instantiate a new instance of the persistence entity. Once instantiated,
	 * the provided value is injected into the item via {@link Item#setItem(Object)}.
	 * </p>
	 * <p>
	 * This method is called internally by the list's mutation operations
	 * (such as {@code add} or {@code addAll}) to ensure that new data is
	 * properly wrapped before being synchronized with the JPA {@code core} list.
	 * </p>
	 *
	 * @param item the inner value (e.g., a String or Date) to be wrapped.
	 *
	 * @return a new, initialized instance of {@code ItemType} containing the item.
	 *
	 * @throws RuntimeException if the {@code ItemType} cannot be instantiated
	 *         (e.g., due to a missing default constructor).
	 * @see #getItemClass()
	 */
	@Override
	public ItemType create(ListType item)
	{
		return ItemUtils.create(getItemClass(), item);
	}
}
